"""
SpatialCPA-v14 — H3D-FLA: a Hybrid 3D Flow-matching Latent Atlas virtual-slice generator
for aligned serial spatial transcriptomics.

v14 implements the ``H3D_FLA_Pipeline.md`` proposal: a **conditional flow-matching** model
in a **joint molecular-morphological latent space**, conditioned on a **3D
positional-attention context** over the real slices, trained **gap-aware** with
**z-marginalization** and **biology-informed regularizers** (interface coherence,
adaptive smoothness, hypoxia-gradient directionality, closed-loop consistency). Virtual
slices are generated by integrating the conditional ODE from noise and decoding the
generated joint latents into expression + cell types, grounded in the real training
biology.

This is a paradigm **completely distinct from v8** (no optimal transport / barycentric
morph / OT fusion / niche MRF — v8 is training-free numpy/scipy) and from v13 (no
cell-sentence tokenizer / gene-language model / retrieval softmax).

    from spatialcpav14 import SpatialCPAv14, SpatialCPAv14Config, Slice, SliceStack
    gen = SpatialCPAv14(stack, gene_names=genes, cell_type_names=types)
    vs = gen.generate_virtual_slice(z=target_z)
"""

from .config import (
    SpatialCPAv14Config, LatentConfig, EncoderConfig, AttnConfig, FlowConfig,
    BioConfig, TrainConfig, GenerationConfig,
)
from .data import Slice, SliceStack
from .latents import ExpressionLatent, morphology_features
from .model import SpatialCPAv14, VirtualSlice

__version__ = "14.0.0"

__all__ = [
    "SpatialCPAv14", "VirtualSlice", "SpatialCPAv14Config", "LatentConfig",
    "EncoderConfig", "AttnConfig", "FlowConfig", "BioConfig", "TrainConfig",
    "GenerationConfig", "Slice", "SliceStack", "ExpressionLatent",
    "morphology_features",
]
