"""Model components: text-grounded embeddings, the noise and anatomical fields, the heads."""

from spatialcpav25_gen.model.embeddings import (
    EntityEmbeddings,
    TextGroundedEmbedding,
    text_embedding_diagnostics,
)
from spatialcpav25_gen.model.field import (
    BBoxClampWarning,
    RotationContext,
    RotationError,
    TriplaneField,
    fourier_encode,
    fourier_encode_dim,
    orientation_rotations,
    random_rotation,
)
from spatialcpav25_gen.model.layout import (
    FlankingSection,
    IntensityHead,
    Layout,
    LayoutError,
    ProposalBudgetWarning,
    RepulsionParams,
    expected_count,
    fit_intensity_head,
    fit_potts_beta,
    fit_repulsion,
    flanking_from_section,
    intensity_fn_from_head,
    mean_cell_density,
    pair_correlation,
    potts_beta_grid,
    potts_smooth,
    sample_layout,
    type_purity,
)
from spatialcpav25_gen.model.noise import (
    GaussianRandomField,
    LengthscaleFit,
    fit_lengthscale_from_sections,
    matern_correlation,
    scaled_distance,
)
from spatialcpav25_gen.model.retrieval import (
    EmptyCandidatePoolWarning,
    InertScoreWarning,
    RetrievalAttention,
    RetrievalIndex,
    attention_entropy,
)

__all__ = [
    "BBoxClampWarning",
    "EmptyCandidatePoolWarning",
    "EntityEmbeddings",
    "FlankingSection",
    "GaussianRandomField",
    "InertScoreWarning",
    "IntensityHead",
    "Layout",
    "LayoutError",
    "LengthscaleFit",
    "ProposalBudgetWarning",
    "RepulsionParams",
    "RetrievalAttention",
    "RetrievalIndex",
    "RotationContext",
    "RotationError",
    "TextGroundedEmbedding",
    "TriplaneField",
    "attention_entropy",
    "expected_count",
    "fit_intensity_head",
    "fit_lengthscale_from_sections",
    "fit_potts_beta",
    "fit_repulsion",
    "flanking_from_section",
    "fourier_encode",
    "fourier_encode_dim",
    "intensity_fn_from_head",
    "matern_correlation",
    "mean_cell_density",
    "orientation_rotations",
    "pair_correlation",
    "potts_beta_grid",
    "potts_smooth",
    "random_rotation",
    "sample_layout",
    "scaled_distance",
    "text_embedding_diagnostics",
    "type_purity",
]
